volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: annalevina/kittygram_backend
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
    volumes:
      - static_volume:/app/collected_static
      - media_volume:/app/media
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: annalevina/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static

  gateway:
    image: annalevina/kittygram_gateway
    volumes:
      - static_volume:/static/
      - media_volume:/media/
    ports:
      - "9000:80"
    depends_on:
      backend:
        condition: service_healthy
